<!--
Para usar em um bloco CMS
---------------------------------------------

<div class="footer-bottom-pagamento">
<div class="title-footer-bottom">Formas de Pagamento</div>
<div><img src="{{media url="wysiwyg/bandeiras_1.jpg"}}" alt=""></div>
</div>
<div class="footer-bottom-entrega">
<div class="title-footer-bottom">Formas de Entrega</div>
<div><img src="{{media url="wysiwyg/entrega_1.jpg"}}" alt=""></div>
</div>
-->

<?php
echo $block->getLayout()
    ->createBlock('Magento\Cms\Block\Block')
    ->setBlockId('footer-bottom')
    ->toHtml();
?>